before_script:
  - "psql -c 'create database tickler_test;' -U postgres"
script: "bundle exec rake travis"
notifications:
  email:
    - josh@isotope11.com
rvm:
  - 1.9.2
  - 1.9.3
  #- rbx-2.0
  #- jruby
env:
  - RAILS_ENV=test
